[target.armv7-unknown-linux-gnueabihf]
linker = "C:\\Program Files (x86)\\Arm GNU Toolchain arm-none-linux-gnueabihf\\14.3 rel1\\bin\\arm-none-linux-gnueabihf-gcc.exe"
ar = "C:\\Program Files (x86)\\Arm GNU Toolchain arm-none-linux-gnueabihf\\14.3 rel1\\bin\\arm-none-linux-gnueabihf-ar.exe"

[env]
CC_armv7_unknown_linux_gnueabihf = "C:\\Program Files (x86)\\Arm GNU Toolchain arm-none-linux-gnueabihf\\14.3 rel1\\bin\\arm-none-linux-gnueabihf-gcc.exe"
AR_armv7_unknown_linux_gnueabihf = "C:\\Program Files (x86)\\Arm GNU Toolchain arm-none-linux-gnueabihf\\14.3 rel1\\bin\\arm-none-linux-gnueabihf-ar.exe"

